import org.gradle.api.tasks.bundling.Jar

plugins {
    id("idea")
    id("java")
    id "net.neoforged.moddev.legacyforge" version "2.0.141"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)
version = "${mod_version}"
group = "trinsdar.advancedsolars" // http://maven.apache.org/guides/mini/guide-naming-conventions.html

base {
    archivesName = "advancedsolars"
}


legacyForge {
    version = "${project.minecraft_version}-${project.forge_version}"
    parchment {
        minecraftVersion = project.minecraft_version
        mappingsVersion = project.mappings_version
    }

    runs {
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
            gameDirectory = project.file('run/server')
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories{
    maven {
        name = 'parchment'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven { url "https://maven.shedaniel.me" }
    maven { url "https://maven.architectury.dev" }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url "https://cursemaven.com"
    }
    maven {
        url 'https://repo.repsy.io/mvn/trinsdar/trins-mods/'
    }
}

dependencies {
    //modImplementation fileTree(include: ['*.jar'], dir: 'libs')
    modImplementation("curse.maven:ic2_classic-242942:8010709")
//    modImplementation("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
//    modImplementation("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    modImplementation("curse.maven:jei-238222:4712866")
    modImplementation("maven.modrinth:carbon-config:HMD2FUea")
    implementation('io.github.trinsdar:trins-wiki-lib:1.0.0'){
        transitive = false
    }
    jarJar('io.github.trinsdar:trins-wiki-lib:1.0.0')
    //modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-forge:${rootProject.rei_version}"
    //modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-plugin-compatibilities-forge:9.1.530"

    modImplementation("me.shedaniel.cloth:cloth-config-forge:8.3.103")
    modCompileOnly("dev.architectury:architectury-forge:6.5.85")
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-forge:9.1.663")
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.mod_version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.mod_version
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : "Trinsdar",
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : "Trinsdar",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}